version: '3.8'

services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: redis-prn2322
    ports:
      - "6379:6379"
    restart: always

  # API Service
  api:
    build:
      context: .
      dockerfile: PRN2322/Dockerfile
    container_name: happybox-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=HappyBoxDb;User Id=Sa;Password=1234567890;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - redis
